---
# tasks file for roles/database

- name: Run Database container
  docker_container:
    name: database
    image: bigboypro/tp-devops-database:latest
    pull: true
    networks:
      - name: app-network
    env:
      POSTGRES_PASSWORD: "{{ vault_postgres_password }}"
    state: started
    restart_policy: unless-stopped
