---
# tasks file for roles/proxy

- name: Run HTTPD container
  docker_container:
    name: httpd
    image: bigboypro/tp-devops-httpd:latest
    pull: true
    networks:
      - name: app-network
    ports:
      - "80:80"
    state: started
    restart_policy: unless-stopped
